import { useCallback, useEffect, useState } from "react";
import { Target, ListChecks, HelpCircle, FolderSearch, CheckCircle2, MessageSquareText, AlertCircle, RefreshCw } from "lucide-react";
import type { ActionPackResponse } from "@/types";
import { api, ApiError } from "@/lib/api";
import { useToast } from "@/lib/toast";
import { Spinner, EmptyState } from "@/components/ui/Feedback";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";

function Section({
  title,
  icon,
  items,
  tone = "slate",
}: {
  title: string;
  icon: React.ReactNode;
  items: string[];
  tone?: "slate" | "brand" | "amber" | "emerald";
}) {
  if (!items.length) return null;
  const tones = {
    slate: "bg-slate-50 border-slate-200 text-slate-600",
    brand: "bg-brand-50 border-brand-100 text-brand-700",
    amber: "bg-amber-50 border-amber-100 text-amber-700",
    emerald: "bg-emerald-50 border-emerald-100 text-emerald-700",
  };
  return (
    <div className={`rounded-xl border p-4 ${tones[tone]}`}>
      <div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide">
        {icon}
        {title}
      </div>
      <ul className="space-y-2">
        {items.map((t, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
            <span className="mt-1 inline-block h-1 w-1 shrink-0 rounded-full bg-slate-400" />
            {t}
          </li>
        ))}
      </ul>
    </div>
  );
}

export function ActionPackContent({ resp }: { resp: ActionPackResponse }) {
  const pack = resp.action_pack;
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-base font-bold text-slate-900">Action Pack</h2>
        {resp.mode === "demo" && <Badge tone="brand">Sample</Badge>}
      </div>

      <Section
        title="Important clauses"
        icon={<ListChecks className="h-3.5 w-3.5" />}
        items={pack.important_clauses}
        tone="brand"
      />
      <Section
        title="Questions to ask the other party"
        icon={<HelpCircle className="h-3.5 w-3.5" />}
        items={pack.questions_to_ask}
        tone="amber"
      />
      <Section
        title="Information to collect"
        icon={<FolderSearch className="h-3.5 w-3.5" />}
        items={pack.info_to_collect}
        tone="slate"
      />
      <Section
        title="Things to clarify"
        icon={<AlertCircle className="h-3.5 w-3.5" />}
        items={pack.things_to_clarify}
        tone="amber"
      />
      <Section
        title="Preparation checklist"
        icon={<CheckCircle2 className="h-3.5 w-3.5" />}
        items={pack.preparation_checklist}
        tone="emerald"
      />
      <Section
        title="Questions for a legal professional"
        icon={<MessageSquareText className="h-3.5 w-3.5" />}
        items={pack.questions_for_legal_professional.map((q) => q.question)}
        tone="brand"
      />

      <p className="rounded-lg bg-slate-50 p-3 text-[11px] text-slate-500">
        Generated by AI. Review with a qualified legal professional before acting on any item.
      </p>
    </div>
  );
}

function friendlyError(e: unknown): string {
  if (e instanceof ApiError) {
    if (e.status === 404) return "Selected document could not be found. It may have been removed.";
    if (e.status === 409) return "This document has not been analyzed yet. Run the analysis first, then generate its Action Pack.";
    return "Could not generate the Action Pack. Please try again.";
  }
  return "Could not generate the Action Pack. Please try again.";
}

export function ActionPackPanel({ documentId }: { documentId: string }) {
  const { push } = useToast();
  const [resp, setResp] = useState<ActionPackResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    api
      .actionPack(documentId)
      .then((p) => { if (!cancelled) setResp(p); })
      .catch((e) => {
        const msg = friendlyError(e);
        if (!cancelled) setError(msg);
        push(msg, "error");
      })
      .finally(() => !cancelled && setLoading(false));
    return () => { cancelled = true; };
  }, [documentId]);

  useEffect(() => {
    const cleanup = load();
    return cleanup;
  }, [load]);

  if (loading) return (
    <div className="flex flex-col items-center justify-center gap-3 py-16 text-sm text-slate-500">
      <Spinner />
      Generating Action Pack&hellip;
    </div>
  );
  if (error) return (
    <div className="flex flex-col items-center justify-center gap-4 py-16 text-center">
      <div className="grid h-14 w-14 place-items-center rounded-2xl bg-red-50 text-red-600">
        <AlertCircle className="h-7 w-7" />
      </div>
      <p className="text-sm text-slate-600">{error}</p>
      <Button variant="secondary" size="sm" onClick={load}>
        <RefreshCw className="h-3.5 w-3.5" /> Retry
      </Button>
    </div>
  );
  if (!resp) return (
    <EmptyState
      icon={<Target className="h-7 w-7" />}
      title="No actions"
      description="No action items available for this document."
    />
  );
  return <ActionPackContent resp={resp} />;
}
